/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassportIndexRouteImport } from './routes/passport.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorPreviewRouteImport } from './routes/vendor.preview'
import { Route as VVendorIdRouteImport } from './routes/v.$vendorId'
import { Route as PassportWalletRouteImport } from './routes/passport.wallet'
import { Route as PassportVendorRouteImport } from './routes/passport.vendor'
import { Route as PassportScanRouteImport } from './routes/passport.scan'
import { Route as PassportRewardsRouteImport } from './routes/passport.rewards'
import { Route as PassportQrRouteImport } from './routes/passport.qr'
import { Route as PassportAdminRouteImport } from './routes/passport.admin'
import { Route as BoothIdRouteImport } from './routes/booth.$id'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminShoppersRouteImport } from './routes/admin.shoppers'
import { Route as AdminEventsRouteImport } from './routes/admin.events'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassportRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorPreviewRoute = VendorPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => VendorRoute,
} as any)
const VVendorIdRoute = VVendorIdRouteImport.update({
  id: '/v/$vendorId',
  path: '/v/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportWalletRoute = PassportWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PassportRoute,
} as any)
const PassportVendorRoute = PassportVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => PassportRoute,
} as any)
const PassportScanRoute = PassportScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PassportRoute,
} as any)
const PassportRewardsRoute = PassportRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => PassportRoute,
} as any)
const PassportQrRoute = PassportQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => PassportRoute,
} as any)
const PassportAdminRoute = PassportAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PassportRoute,
} as any)
const BoothIdRoute = BoothIdRouteImport.update({
  id: '/booth/$id',
  path: '/booth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShoppersRoute = AdminShoppersRouteImport.update({
  id: '/shoppers',
  path: '/shoppers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/passport': typeof PassportRouteWithChildren
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/shoppers': typeof AdminShoppersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/booth/$id': typeof BoothIdRoute
  '/passport/admin': typeof PassportAdminRoute
  '/passport/qr': typeof PassportQrRoute
  '/passport/rewards': typeof PassportRewardsRoute
  '/passport/scan': typeof PassportScanRoute
  '/passport/vendor': typeof PassportVendorRoute
  '/passport/wallet': typeof PassportWalletRoute
  '/v/$vendorId': typeof VVendorIdRoute
  '/vendor/preview': typeof VendorPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/passport/': typeof PassportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/shoppers': typeof AdminShoppersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/booth/$id': typeof BoothIdRoute
  '/passport/admin': typeof PassportAdminRoute
  '/passport/qr': typeof PassportQrRoute
  '/passport/rewards': typeof PassportRewardsRoute
  '/passport/scan': typeof PassportScanRoute
  '/passport/vendor': typeof PassportVendorRoute
  '/passport/wallet': typeof PassportWalletRoute
  '/v/$vendorId': typeof VVendorIdRoute
  '/vendor/preview': typeof VendorPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/passport': typeof PassportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/passport': typeof PassportRouteWithChildren
  '/profile': typeof ProfileRoute
  '/qr': typeof QrRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/shoppers': typeof AdminShoppersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/booth/$id': typeof BoothIdRoute
  '/passport/admin': typeof PassportAdminRoute
  '/passport/qr': typeof PassportQrRoute
  '/passport/rewards': typeof PassportRewardsRoute
  '/passport/scan': typeof PassportScanRoute
  '/passport/vendor': typeof PassportVendorRoute
  '/passport/wallet': typeof PassportWalletRoute
  '/v/$vendorId': typeof VVendorIdRoute
  '/vendor/preview': typeof VendorPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/passport/': typeof PassportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/following'
    | '/login'
    | '/map'
    | '/passport'
    | '/profile'
    | '/qr'
    | '/sitemap.xml'
    | '/vendor'
    | '/welcome'
    | '/admin/events'
    | '/admin/shoppers'
    | '/admin/vendors'
    | '/booth/$id'
    | '/passport/admin'
    | '/passport/qr'
    | '/passport/rewards'
    | '/passport/scan'
    | '/passport/vendor'
    | '/passport/wallet'
    | '/v/$vendorId'
    | '/vendor/preview'
    | '/admin/'
    | '/passport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/following'
    | '/login'
    | '/map'
    | '/profile'
    | '/qr'
    | '/sitemap.xml'
    | '/vendor'
    | '/welcome'
    | '/admin/events'
    | '/admin/shoppers'
    | '/admin/vendors'
    | '/booth/$id'
    | '/passport/admin'
    | '/passport/qr'
    | '/passport/rewards'
    | '/passport/scan'
    | '/passport/vendor'
    | '/passport/wallet'
    | '/v/$vendorId'
    | '/vendor/preview'
    | '/admin'
    | '/passport'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/following'
    | '/login'
    | '/map'
    | '/passport'
    | '/profile'
    | '/qr'
    | '/sitemap.xml'
    | '/vendor'
    | '/welcome'
    | '/admin/events'
    | '/admin/shoppers'
    | '/admin/vendors'
    | '/booth/$id'
    | '/passport/admin'
    | '/passport/qr'
    | '/passport/rewards'
    | '/passport/scan'
    | '/passport/vendor'
    | '/passport/wallet'
    | '/v/$vendorId'
    | '/vendor/preview'
    | '/admin/'
    | '/passport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsRoute: typeof EventsRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PassportRoute: typeof PassportRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QrRoute: typeof QrRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorRoute: typeof VendorRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  BoothIdRoute: typeof BoothIdRoute
  VVendorIdRoute: typeof VVendorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/': {
      id: '/passport/'
      path: '/'
      fullPath: '/passport/'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof PassportRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/preview': {
      id: '/vendor/preview'
      path: '/preview'
      fullPath: '/vendor/preview'
      preLoaderRoute: typeof VendorPreviewRouteImport
      parentRoute: typeof VendorRoute
    }
    '/v/$vendorId': {
      id: '/v/$vendorId'
      path: '/v/$vendorId'
      fullPath: '/v/$vendorId'
      preLoaderRoute: typeof VVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/wallet': {
      id: '/passport/wallet'
      path: '/wallet'
      fullPath: '/passport/wallet'
      preLoaderRoute: typeof PassportWalletRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/vendor': {
      id: '/passport/vendor'
      path: '/vendor'
      fullPath: '/passport/vendor'
      preLoaderRoute: typeof PassportVendorRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/scan': {
      id: '/passport/scan'
      path: '/scan'
      fullPath: '/passport/scan'
      preLoaderRoute: typeof PassportScanRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/rewards': {
      id: '/passport/rewards'
      path: '/rewards'
      fullPath: '/passport/rewards'
      preLoaderRoute: typeof PassportRewardsRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/qr': {
      id: '/passport/qr'
      path: '/qr'
      fullPath: '/passport/qr'
      preLoaderRoute: typeof PassportQrRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/admin': {
      id: '/passport/admin'
      path: '/admin'
      fullPath: '/passport/admin'
      preLoaderRoute: typeof PassportAdminRouteImport
      parentRoute: typeof PassportRoute
    }
    '/booth/$id': {
      id: '/booth/$id'
      path: '/booth/$id'
      fullPath: '/booth/$id'
      preLoaderRoute: typeof BoothIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shoppers': {
      id: '/admin/shoppers'
      path: '/shoppers'
      fullPath: '/admin/shoppers'
      preLoaderRoute: typeof AdminShoppersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminShoppersRoute: typeof AdminShoppersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminShoppersRoute: AdminShoppersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PassportRouteChildren {
  PassportAdminRoute: typeof PassportAdminRoute
  PassportQrRoute: typeof PassportQrRoute
  PassportRewardsRoute: typeof PassportRewardsRoute
  PassportScanRoute: typeof PassportScanRoute
  PassportVendorRoute: typeof PassportVendorRoute
  PassportWalletRoute: typeof PassportWalletRoute
  PassportIndexRoute: typeof PassportIndexRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportAdminRoute: PassportAdminRoute,
  PassportQrRoute: PassportQrRoute,
  PassportRewardsRoute: PassportRewardsRoute,
  PassportScanRoute: PassportScanRoute,
  PassportVendorRoute: PassportVendorRoute,
  PassportWalletRoute: PassportWalletRoute,
  PassportIndexRoute: PassportIndexRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

interface VendorRouteChildren {
  VendorPreviewRoute: typeof VendorPreviewRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorPreviewRoute: VendorPreviewRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsRoute: EventsRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PassportRoute: PassportRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QrRoute: QrRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorRoute: VendorRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  BoothIdRoute: BoothIdRoute,
  VVendorIdRoute: VVendorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
